### ISSUE TITLE
Chrome Custom Tabs should have ability to adjust

### ISSUE THREAD

**Issue by MikolajKakol** [auth0/Auth0.Android#106]
It's great that you have added support for Chrome Custom Tabs but we really need ability to alter in it's builder. I'd love to change color and display title instead of url.
Any plans on adding that or ways to nicely hack it?

**Comment by lbalmaceda** [comment]
Hi, @novemberox. Thanks for the feedback! 
I'm open to making it get the color from a custom style. Because it's just 1 attribute it doesn't make sense to have a builder method for customizing it. Also, there's no way to hide the URL. This is by design of the CCT so the user knows every time where they are navigating. There's an option though that it's to show the title and the URL as shown in the pretty screenshot below. 😄 I don't think this one is necessary. What's your use case or why do you think you might need to show it?

![image](https://user-images.githubusercontent.com/3900123/28116694-93378b60-66e0-11e7-9d79-dee402e1d699.png)

**Comment by MikolajKakol** [comment]
My use case is nothing special. I just wanted to show title, so it might be nicer to users. Just bare in mind that application theme might be different than rest of application to create better application launch experiences (https://speakerdeck.com/cyrilmottier/launch-screens-from-a-tap-to-your-app). Also it might be nice to customize animations or add action button (maybe with help?) who knows how business would like to enrich experiences.
That being said. What is most important for me right now is the color.

**Comment by ashishbhandari** [comment]
Well I have a one use case where I usually need it, I have one code base through which I can create multiple package build for different business partners, hence package name is different so for each partners I need to register it in google API console for Google login and Facebook developer account for facebook login, I want to get rid of this repetitive task  where I want to bring SSO for all partners so that only one master account is required to register in different developer console and login and signup process could be smoother using custom tab experience. 

Where I can keep this in web and provide the Single Oauth experience using Chrome tab experience for business aprtners.

**Comment by KennethFindMy** [comment]
Hi @lbalmaceda, how can you change the toolbar color? 
I am using react-native-auth0, and authorize(), but i would like to change the color of the toolbar.
