### ISSUE TITLE
Cancelling web authentication doesn't fire failure event

### ISSUE THREAD

**Issue by dj-mal** [auth0/Auth0.Android#140]
After the changes in #120, when a user cancels the web authentication, the OAuth manager would recognize that the `AuthorizeResult` is invalid and return false straight away, without calling `onFailure` in the callback. 

This causes problem if the client app is stuck, waiting for the result of the Authentication, as there is no other way to detect whether the authentication process has completed or not. 

Is it possible to add `callback.onFailure(new AuthenticationException("Invalid Authorize Result"))` before returning `false` in the following blocks?
* https://github.com/auth0/Auth0.Android/blob/2565cdb13f065deb2ec1d8715a512ac0de4d32cb/auth0/src/main/java/com/auth0/android/provider/OAuthManager.java#L105-L108
* https://github.com/auth0/Auth0.Android/blob/2565cdb13f065deb2ec1d8715a512ac0de4d32cb/auth0/src/main/java/com/auth0/android/provider/OAuthManager.java#L110-L114

And also adding an else clause to trigger the callback in `AuthenticationActivity` 
* https://github.com/auth0/Auth0.Android/blob/2565cdb13f065deb2ec1d8715a512ac0de4d32cb/auth0/src/main/java/com/auth0/android/provider/AuthenticationActivity.java#L80-L82

So that the client app would know the web authentication process has completed without success?

**Comment by lbalmaceda** [comment]
The "auth canceled" was never intended, thus that PR fixing the error. But we have already marked this as a nice-to-have feature and will consider it for a future version. If we enumerate the snippets:
- The first one corresponds to a result that needs to be **ignored** because of calling `WebAuthProvider#resume` with a different code than the expected.
- The second one corresponds to a valid code but invalid data when calling `WebAuthProvider#resume`, thus we're incapable of parsing it and results in a failure. We can argue if this case should call `callback#onFailure` or just **ignore it** like we do now. But responses from our hosted login page always contain those values. So we should probably keep ignoring it.
- The third one is were we check the result after the browser is closed, either because of a successful authentication or because the user closed the browser by pressing back. This is were the change should be introduced to support a "cancel" callback.

Related https://github.com/auth0/Auth0.Android/issues/127

**Comment by rakeshostwal** [comment]
Is it fixed now? We are not getting any callback when user clicks on close button before getting auth result which results in screen getting stuck waiting for the response.
