### ISSUE TITLE
Legacy grant type is not allowed for the client

### ISSUE THREAD

**Issue by tplkn** [auth0/Auth0.Android#154]
We disabled legacy grand types in our Auth0 settings.
Now when I'm trying to sign up/login I get "Grant type 'http://auth0.com/oauth/legacy/grant-type/ro' not allowed for the client."
I've tried to enable "OIDCConformant", but I got `access_denied` `Unauthorized`
How can fix this issue?
I'm using the last version of this SDK (1.12.2).

**Comment by lbalmaceda** [comment]
Please enable the the local flag https://github.com/auth0/Auth0.Android#oidc-conformant-mode

**Comment by tplkn** [comment]
@lbalmaceda 
my code is
```
final Auth0 auth0 = new Auth0(clientId, domain);
auth0.setOIDCConformant(true);
this.authentication = new AuthenticationAPIClient(auth0);
this.authenticatior.login(usernameOrEmail, password, realmOrConnection).setScope(...).start(...)
```
I'm getting `access_denied Unauthorized` as I mentioned before.

**Comment by lbalmaceda** [comment]
When you call `auth0.setOIDCConformant(true)` the client will use the `/oauth/token` endpoint instead of `/ro`. Check in your `Client | Settings | Advanced Settings | Grant Types` that the `PASSWORD` scope is allowed. Don't forget to save the settings 👍 

![image](https://user-images.githubusercontent.com/3900123/37976376-c3173ce8-31b7-11e8-8eb9-459acd428686.png)

If you have further questions regarding the platform, please contact our amazing support at https://support.auth0.com ⭐️

**Comment by tplkn** [comment]
"Password" is enabled. 
Moreover we're migrating from a legacy flow and js version (auth0-js) works fine.

**Comment by lbalmaceda** [comment]
That's all you have to do. The client you use on your mobile app should be of type `native`, the grant must be enabled and the api client should be set as OIDC conformant on the java code. Check the logs in the auth0 site or [enable the local logging](https://github.com/auth0/Auth0.Android/blob/master/auth0/src/main/java/com/auth0/android/Auth0.java#L204) to discover what is happening behind and why is it failing. I can't help you any further since this is not an SDK issue. Please, use the support url above.
