### ISSUE TITLE
Can't logout from Webclient

### ISSUE THREAD

**Issue by Viked** [auth0/Auth0.Android#155]
Hello,
I am using this code to start auth process :

    Auth0 auth0 = new Auth0(AppConfig.auth0clientId, AppConfig.auth0domain);
auth0 = Utils.getAuth0();
        WebAuthProvider.init(auth0)
               .withParameters(parameters)
                .withScheme(getString(R.string.scheme))
                .withScope(Config.Auth0.scopeValue)
                .start(this, callback);

Parameters contains "prompt": "login"

And login/registration flow works perfectly. 
When try to logout - it automatically login me to the app.

Used just email/password auth.
SDK version 'com.auth0.android:auth0:1.12.0'

**Comment by Viked** [comment]
Clean token from local storage. Should I use some methods from sdk for the log out?
I tried to use some method to clear credentials from sdk, but it was not help.

**Comment by lbalmaceda** [comment]
@Viked If you are using the `WebAuthProvider`, you're using a browser app to authenticate (i.e. Chrome). This SDK **cannot** clear the browser cookies for you, and tbh I don't think any other android app can, only the browser itself. Unless the browser apps expose an API to do so from an external app. That being said, how you handle the "logged in" state is up to you. You can implement your own logic to store and remove credentials from memory or `SharedPreferences` file or use our [Credential Managers](https://github.com/auth0/Auth0.Android#credentials-manager) to simplify that. But there's no "logging out" method available on this SDK.

Calling the `WebAuthProvider` passing `prompt=login` should force show the Lock widget (Universal Login) and thus, making the user input their credentials or click a social button manually before returning to the application. This is _if you are not_ passing a valid `connection` parameter too, since that will skip showing Lock. That's all it does the `prompt` parameter and that's how it should work. If that feature works or not, that's not part of this SDK either so you'll have to reach our support team at https://support.auth0.com to fill the issue.

I you find an SDK issue feel free to reopen this issue or create a new one.
Cheers

**Comment by dustin-graham** [comment]
I read the docs here: https://auth0.com/docs/logout

and I believe it would be an easy fix to add logout functionality to this library. It simply needs to open a new ChromeCustomTab to the logout url for the user's tenant. I've tested this myself and it works perfectly. It takes a very small amount of code to accomplish. There is even support for a redirect and I believe that could be leveraged for several other special handling features as well. 

I'd like to request that this be re-opened, addressed, and an update published. This is essential functionality. Without it, it is very difficult for end users to log into anything except the very first identity they used. they have to go to chrome, clear their cookies and come back to the app. This is not a workable solution. Please address this issue.

**Comment by dustin-graham** [comment]
@lbalmaceda to go along with my suggested behavior posted above, this is precisely what the Auth0.Swift library does: https://github.com/auth0/Auth0.swift. Please re-open this issue and resolve.

**Comment by kushanshah11** [comment]
@lbalmaceda you are right using that login page appears everytime even if user not logout from app.login page only appears when user logout otherwise it should directly go to particular dashboard of app.

even swiftIos have clearSession code which is not available on Android Sdk.

hope you understand what i want to say.

Thanks.

**Comment by lbalmaceda** [comment]
@kushanshah11 I understand the request and will re-evaluate including this with the team. I'll keep the issue open.
In the meantime you could achieve the same result by calling the intent yourself as explained [here](https://auth0.com/docs/api/authentication#logout). You need to send the `client_id` and the `returnTo` parameters. The second should be an URL to the same callback URL you have whitelisted in the application's dashboard, which should as well be whitelisted in the allowed logout URLs section.

**Comment by bpappin** [comment]
Just an FIY, normally ups simply need to clear the client tokens on most mobile APIs, since there is no way to get new ones without authenticating.

What advantage does calling the /v2/logout endpoint give the application?

**Comment by lbalmaceda** [comment]
> What advantage does calling the /v2/logout endpoint give the application?

It would make the universal login page not to remember the previous account you used to log in. So you would see the login form as if it's the first time you're logging in.

**Comment by bpappin** [comment]
You mean that the universal login page (not the IDP page) remembers your authentication information (like your username)? That's not logging out then, it's simply removing a cookie.

Normally a mobile app should *just* need to destroy its access (and refresh) token(s) to logout, since it must then re-authenticate to retrieve either.

**Comment by dustin-graham** [comment]
@bpappin , @lbalmaceda , We're using Azure AD with Auth0. The issue for us is that the login page for Azure AD needs this endpoint to be called if you want to truly "logout". This is because Chrome is maintaining state in this case. Clearing our own stored credentials in the app is only one part of the logout process. The other half is getting the 3rd party login provider to clear its state in your browser. If you don't call the logout method, the next time you go to login the Azure AD page will not allow you to switch accounts and the user gets stuck with the original account that was logged in. The only way to fix this is to go to clear your Chrome browser data and then go login again. Cleaning up this 3rd party state is the purpose of the logout endpoint. Since this library does not support it, I've had to hack around the issue and issue the logout command to a Chrome Web Tab myself. Of course this is not a necessary hack on my iOS app since the Auth0 library implements this essential functionality. It would be very much appreciated if the Android library would do the same.

**Comment by ppetarr** [comment]
@dustin-graham You mentioned being able to successfully call the logout api? Do you have a sample of what that might look like? I'm currently calling it through a CustomTabIntent however when I specify the `redirectTo` parameter, it always fails with a 400, but when I remove the `redirectTo` I get a 200 but then I'm stuck on that page with no redirect.

**Comment by dustin-graham** [comment]
I am not using the redirect either. It's been almost a year since I
implemented it so the details of this are a bit lost to time. But I faintly
remember some difficult here. Since the iOS SDK supports logout, I'm using
that and it successfully redirects back to my app. But On Android my users
have to close the chrome tab themselves.

**Comment by ppetarr** [comment]
@dustin-graham thanks for the update. That's really unfortunate, I believe I do have a solution at least one that seems to be working for the time being. 

When calling the `v2/logout` you have to set `federated`, `redirectTo` and `client_id` and it has to be opened via CustomTabsIntent.

 Once the call is made, a redirect is called to your specified url which in turn should be handled by the `Activity` that started the call through the `<intent-filter>` similar to the way the `RedirectActivity` works within the current auth0 SDK. Then you can proceed with your normal logout flow, if you check the logs on Auth0 you should see a `Successful Logout` call. 

An additional note if the Activity that starts your logout call is not the same as your login, you will need a unique `scheme/host` specified in the `Allowed Logout URLs` and you will have to account for these changes in your `<intent-filter>` that way the app will be able to re-direct appropriately.

**Comment by lbalmaceda** [comment]
@ppetarr @kushanshah11 @Viked we've been working on the logout feature on this PR. Feel free to try it and drop your feedback!

**Comment by lbalmaceda** [comment]
Will be available in next minor release.

**Comment by CarsonRedeye** [comment]
Is there plans to add the ability to add the `federated` query param via the SDK?

**Comment by lbalmaceda** [comment]
@CarsonRedeye not in the short term. The behavior of `federated` fluctuates a lot depending on the identity provider that it targets and we can't provide it as a solution that fits it all. i.e. google with multiple accounts logged in.
