### ISSUE TITLE
Problem with Sign up and Log in

### ISSUE THREAD

**Issue by alex96frolov** [auth0/Auth0.Android#156]
Hi! I have an a issue with signing up and logging in using Auh0 in android. Trying to sign up via client.signUp(email, password, connection).start() results me in failure, AuthenticationException says me there is 404 not found. When trying to sign up under the same email is also returning me 404 but the message is "Email already signed up". And web admin is seeing this user in database so we can say that user is really signed up. The same is happening with the login to the system.  Getting 404 and nothing more. Can you explain please what is going wrong?

**Comment by imetodieva** [comment]
Hello, I am using the library to register and login a user with db connection.Since of today I have the error "a0.sdk.internal_error.unknown" with code 0 .The issue occurs only with Android .Probably the error comes from the latest updates and depreciations but I haven't read about any which I am using .Please look into the issue .

**Comment by BesatZardoshtCarfax** [comment]
I have exactly same issue using AuthenticationAPIClient for sign up.

```
val clientId = "my_client_id"
val domain = "my_domain"
val email = "myemail@email.com"
val password = "myPassword"
val connection = "my_email_connection"
val account: Auth0 = Auth0(clientId, domain)
val authenticationAPIClient = AuthenticationAPIClient(account)
authenticationAPIClient.signUp(email, password, connection).start(signUpCallback)
```
