### ISSUE TITLE
Incorrect MFA exception check isMultifactorRequired

### ISSUE THREAD

**Issue by tplkn** [auth0/Auth0.Android#158]
class AuthenticationException
```
    /// When MFA code is required to authenticate
    public boolean isMultifactorRequired() {
        return "a0.mfa_required".equals(code);
    }
```
but original code is `mfa_required`

**Comment by tplkn** [comment]
Note: when I login with Google auth the code is `a0.mfa_required`. Previous comment for email/password login

**Comment by tplkn** [comment]
OIDCConformant is true
The problem is
email/login => mfa_required
google => a0.mfa_required
I'm calling following code for google auth
```
 WebAuthProvider.init(auth0)
            .withConnection("google-oauth2")
            .withScope(Auth0Client.SCOPES)
            .start(...)
```

**Comment by lbalmaceda** [comment]
```
email/login => mfa_required
```` 
this is fine, just like I said it happens on the `/oauth/token` endpoint.


However when using the `WebAuthProvider` class, what you're launching is authentication via a Browser app which uses Lock web and redirects back to the app. The app receives a `code` and sends that along with the `code_verifier` to the `/oauth/token` endpoint to perform a code exchange and obtain the final tokens. I've just tried this with a google account, setting up MFA right in the browser using Authy on my phone, and after finishing the flow the tokens where received fine. I did not receive a `a0.mfa_required` error. Please check if you're changing something in between and don't hesitate to contact support to get more guidance on this https://support.auth0.com. I'll leave the issue open since the PR with the error_code fix is not yet merged.
