### ISSUE TITLE
Auth0 Android Integration With Google + Facebook

### ISSUE THREAD

**Issue by nahba** [auth0/Auth0.Android#183]
Hi there,

I need to use Auth0.Android SDK for signup with Google + Facebook with my own UI. I do not need to use Lock.Android SDK as it does not fit in. I did not find any sample which shows Auth0.Android SDK integration with Google + Facebook. Is there any way to do that?

**My Requirements:** When user clicks on Google/Facebook button in my screen (I have designed as per my application theme, I do not want to use what Auth0 provides), it should perform sign up/login process and directly redirect to next screen rather redirecting back to sign up/login screen again.

Is this possible with Auth0.Android SDK?

Thanks

**Comment by lbalmaceda** [comment]
As of today, the only way you can login/signup using a social provider such as Facebook or Google is using the [Universal Login Page](https://auth0.com/docs/guides/login/universal-vs-embedded). By clicking a button, you redirect the user to that page hosted by Auth0 and the user will see the Lock widget. You can also send the `connection` parameter so that the widget is not shown and it skips to the social provider's login page.

See [here](https://github.com/auth0/Auth0.Android#authentication-with-universal-login) for details on how to set up this and [here](https://github.com/auth0/Auth0.Android#authenticate-with-any-auth0-connection) to learn how to specify a connection.

**Comment by alikyo** [comment]
Hi,

What is the correct connection name for Google.

Is it `.withConnection("google")` or `.withConnection("google-oauth2")`

I am getting different error for each one and I don't know which is to correct connection name so I can focus on the missing configuration.

Thanks

**Comment by lbalmaceda** [comment]
@alikyo you can check the `name` of a given connection if you click its logo in [this section](https://manage.auth0.com/#/connections/social) of the dashboard
