### ISSUE TITLE
RequestFactory does not set custom user agent string in request headings when device using Microsoft Edge browser

### ISSUE THREAD

**Issue by spacemase** [auth0/Auth0.Android#222]
### Description

Our Android users are blocked from logging in if their device has Microsoft Edge selected as their default browser.  When the `AuthenticationAPIClient` sets a custom user agent string in the RequestFactory, the request itself does not include that user agent string.  Rather it contains the Edge browser's default user agent string.  This prevents our specific authentication callbacks from being issued from the webview and login does not complete.  Problem started when users began using Microsoft Edge browser (no code has changed in our implementation).

### Prerequisites

[* ] I have checked the documentation for this library [Add a link].

[* ] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.

[* ] I have checked for related or duplicate [Issues](https://github.com/auth0/Auth0.Android/issues) and [PRs](https://github.com/auth0/Auth0.Android/pulls).

[* ] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).

[* ] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Environment

Please provide the following:

- Version of Auth0.Android used:  1.13.2
- Version of Android being used:  any
- Additional packages that might be affecting your instance:  Microsoft Edge webview

### Reproduction

Setup a Auth0 instance that will call the com.auth0.android.provider.RedirectActivity with the result callback.  Test login using WebAuthProvider.  Note that the com.auth0.android.provider.RedirectActivity never invokes the AuthCallback supplied to WebAuthProvider::start

- all Android devices using Microsoft Edge browser

**Comment by lbalmaceda** [comment]
The `AuthenticationAPIClient#setUserAgent()` call you do will affect requests performed by that instance of the API client. When using the `WebAuthProvider` with _PKCE_, a new instance of that client is [generated with the default params](https://github.com/auth0/Auth0.Android/blob/master/auth0/src/main/java/com/auth0/android/provider/OAuthManager.java#L253). This instance historically has never been open for customization, and since it's a new one it won't contain any custom user-agent. Nevertheless, this instance is only used to call the token-exchange endpoint in order to receive the auth0 credentials. If this step was reached it means the browser has successfully called back your application with the `code` property it will later exchange for credentials.

I find confusing the way you described how you're attempting to log in a user. Please, take a look at [this guidance in the README](https://github.com/auth0/Auth0.Android#authentication-with-universal-login) and confirm we're on the same page. That said, if this was working before I suggest you double check your end as we haven't changed this code in a long time as well.

**Comment by spacemase** [comment]
Thanks for the attention Luciano.  Have been working with my backend team and I see this was a false issue.  We have a different problem.  The User Agent string is not intended to be changed in the web authentication flows.  This issue may be closed with my apologies for the false alarm!
