### ISSUE TITLE
Auth0 renewAuth fails to propagate http status code to AuthenticationException in onFailure

### ISSUE THREAD

**Issue by dcostinett** [auth0/Auth0.Android#234]
### Description

I’m working on an Android app and getting an unexpected response from the renewAuth API call when I try to refresh a token. The process works fine up until the token gets invalidated on the back-end. When I get a response with the http response code 403 Forbidden with body:

{“error”:“invalid_grant”,“error_description”:“Unknown or invalid refresh token.”}

what I want to do is check the AuthenticationException object in the callback and I expect that that error object will have the statusCode set to 403 to match the http response status code, but the value it holds is 0:

### Prerequisites

[x] I have checked the documentation for this library [Add a link].

[x] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.
I posted this issue there too.

[x] I have checked for related or duplicate [Issues](https://github.com/auth0/Auth0.Android/issues) and [PRs](https://github.com/auth0/Auth0.Android/pulls).

[x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).

[x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Environment

Please provide the following:

- Version of Auth0.Android used: 1.15.1
- Version of Android being used: API 21 to API 28 (Android 5.0 Lollipop to Q). App built targetting API 28, using AndroidX.
- Additional packages that might be affecting your instance: Retrofit 2.4.0, OkHttp 3.14.1

### Reproduction

With a valid Auth0 refresh token we call the renewAuth SDK method and get a 403 http status code 
![charles_clip](https://user-images.githubusercontent.com/2453774/58343404-bcdd4780-7e07-11e9-80ff-38f9a8d23a05.png)
response from the service which fires the onFailure method of the callback. Examine the AuthenticationException object's statusCode property and I expect to see the status code there match the http status code. But it appears the AuthenticationException(String, String) constructor is called rather than the AuthenticationException(

Please include:

- Specific devices affected
Galaxy S9, Pixel 2 XL
- Log files or stacktraces (redact/remove sensitive information)
- Snippet of the code you're running (redact/remove sensitive information)
    override fun refreshToken(): Single<Boolean> {
        return Single.create<Boolean> {
            authClient.renewAuth(profileService.getRefreshToken())
                    .start(object : BaseCallback<Credentials, AuthenticationException> {
                        override fun onSuccess(payload: Credentials?) {
                            payload?.accessToken?.let { token ->
                                profileService.updateAuthToken(token)
                            }
                            payload?.refreshToken?.let { token ->
                                profileService.updateRefreshToken(token)
                            }
                            it.onSuccess(true)
                        }

                        override fun onFailure(error: AuthenticationException?) {
                            // return false if we get a 403 or a 401...
                            if (error?.statusCode == CODE_ERROR_FORBIDDEN || error?.statusCode == CODE_ERROR_UNAUTHORIZED) {
                                if (!BuildConfig.DEBUG) {
                                    NewRelic.recordHandledException(error)
                                }
                                Log.e(this::class.tag, "Error code = ${error.code}, description = ${error.description}")
                                it.onSuccess(false)
                            } else {
                                // ... or accessDenied, otherwise, we don't want to clear the token
                                it.onSuccess(error?.isAccessDenied != true)
                            }
                        }
                    })
        }.retryWhen {
            retryHandler(it, 3, 2) { ex, i ->
                if (!BuildConfig.DEBUG) {
                    NewRelic.recordCustomEvent("Authorization", "RefreshTokenFailure:", mapOf(Pair(i.toString(), ex.message)))
                }
            }
        }
    }

- Screenshots, if helpful

![image](https://user-images.githubusercontent.com/2453774/58343704-91a72800-7e08-11e9-893e-981da8e74b0b.png)

**Comment by lbalmaceda** [comment]
Thanks for filling the details. Yes.. in fact is [using the Map constructor](https://github.com/auth0/Auth0.Android/blob/master/auth0/src/main/java/com/auth0/android/request/internal/BaseRequest.java#L137) as it's reading the response body as JSON. In this case, a request to renew a token that fails means either that the request failed due to networks reasons (e.g. [cause of the exception is Auth0Exception](https://github.com/auth0/Auth0.Android/blob/master/auth0/src/main/java/com/auth0/android/request/internal/BaseRequest.java#L142)) or the refresh token was revoked. For the last case, other than re-logging the users, there's no alternative path..
Can I ask why you need to check the status code? It's not clear to me after reading the snippet you shared.

**Comment by dcostinett** [comment]
I specifically want to distinguish between network issues and an explicit revocation of the token -- 401/403. When I get the 401/403 I want to log out the user and ask them to log back in, but I want to avoid doing that for a simple network blip with the mobile device. At the point where I'm looking at the AuthenticationException I don't have easy access to the http status code other than from the AuthenticationException itself.

**Comment by lbalmaceda** [comment]
After re-checking the classes, any network error should trigger a call to [onFailure](https://github.com/auth0/Auth0.Android/blob/master/auth0/src/main/java/com/auth0/android/request/internal/BaseRequest.java#L149-L152) (or throw the exception in case of a sync call). The `parseUnsuccessfulResponse` method will only be called on those requests that succeed but have a status code other than 2xx. 

I think the solution here is to create a different error type in that method so that you can easily check that scenario by calling something similar to `exception.isNetworkError()`. There's no need to dig deeper in the status codes or manually parsing the error description. I'll add a task to review this in the next 2 weeks.

**Comment by lbalmaceda** [comment]
@dcostinett I've proposed a solution. Feel free to try it and leave feedback 🌮 🎉

**Comment by dcostinett** [comment]
Hi Ibalmaceda, sorry about the delay here... I am getting a call to the onFailure method with the AuthorizationException getting passed in with the statusCode value set to 0. Are you suggesting that I should get a call to the parseUnsuccessfulResponse method as well? The method here is the implementation of Auth0's callback to the start method on the renewAuth call. I'm nost sure how I would implement a new error type. Can you please elaborate?

**Comment by lbalmaceda** [comment]
Please checkout the branch from the PR linked to this issue. Once you do, if you use that code in your app you'll now be able to distinguish a network error from an API/server error.

Please use `isNetworkError()` on the AuthenticationException that you receive in order to tell this. 

```
if (error.isNetworkError()){
  //handle network error differently 
}
```

As mentioned before, there's no need to manually check the HTTP status code.

**Comment by dcostinett** [comment]
That seems like it will be better than parsing the string in the error “code”. 

Thanks,
Dan
