### ISSUE TITLE
AuthenticationException when "don't keep activity" option is on

### ISSUE THREAD

**Issue by sklr13** [auth0/Auth0.Android#242]
I use WebAuthProvider for sign in into my app and I have a problem with it. 
If you turn on in developers options "don't keep activity" item you will always receive AuthenticationException in AuthCallback. 
This item help us to handle error situations wihch can appears when the system has a luck of resource.
Without this feature all works fine and we receive onSucces with the same credentials.
I tested on OnePlus 3T,Galaxy S8 and Google Pixel.

![image (1)](https://user-images.githubusercontent.com/25431574/59676837-249d6d00-91d1-11e9-9b7e-84b12de13b98.png)

**Comment by lbalmaceda** [comment]
@sklr13 Last time I checked the `WebAuthProvider` logic relied on a in-memory instance of itself to handle the result on the way back. If that setting is on, it would mean that the activity would be not only destroyed but also removed from memory. Like you said, this happens when the OS decides it lacks RAM and needs to start killing background apps and services to make some room.

I never run into such error but I know you can trigger it with that setting. I'll leave this open as a reminder that this if something we should eventually look at, but note this issue is not a high priority for us.

**Comment by lbalmaceda** [comment]
There's not much we can do. We need to keep an instance somewhere to hold the callback that the user passes. That's the only way we can handle this flow automatically for them. If not, you'd need to define your own intent filter, class that handles the interaction, token exchange, and error/result parsing.
