### ISSUE TITLE
Not able to login native social network

### ISSUE THREAD

**Issue by emejia160** [auth0/Auth0.Android#262]
We are currently developing a native application for Android and iOS, we are in the process of logging in to social networks, we are using the Facebook native SDK to obtain the user token, then we authenticate in Auth0 using the loginWithOAuthAccessToken method, but it does not work properly and we receive a negative response, additionally, we cannot use the native form of auth0, since we have to build our own user interface. Any suggestions on how we could do this login? thanks

**Comment by lbalmaceda** [comment]
Using an external login provider such as Facebook or Google is something we stopped supporting in the past 2 years or so. Some of the docs you can find on the auth0 site have a header on the top recommending the use of web-auth flows, and it's pros/cons with that other endpoint you mentioned.

>This feature relies on a deprecated grant type. Applications created after June 8th 2017 won't be able to use this feature. We recommend using browser-based flows, as explained in Web-based auth.

The reason you receive a negative response could be because your auth0 account was created after the date above ☝️. I think it makes sense to deprecate this library's method now that most of the accounts won't be able to consume it.

By Native Auth0 I guess you mean Lock.Android and Lock.Swift libraries. They also rely on these SDKs so would run into the same situation.

There's an ongoing effort to re-add an endpoint that can resolve this at least for Facebook initially, but no firm dates yet.
