### ISSUE TITLE
Logout crash

### ISSUE THREAD

**Issue by smedic** [auth0/Auth0.Android#284]
When I try to logout, app crashes. 

```kotlin
fun logout(activity: Activity, callback: OnAuth0Result) {
        WebAuthProvider.logout(auth0!!)
            .withScheme("demo")
            .start(
                activity,
                object : VoidCallback {
                   override fun onSuccess(payload: Void) {
                       callback.onSuccess()
                   }

                   override fun onFailure(error: Auth0Exception) {
                       callback.onError(AuthenticationException(error.message))
                   }
            })
    }
```

<img width="1214" alt="Screen Shot 2020-02-07 at 3 09 09 PM" src="https://user-images.githubusercontent.com/10304831/74036148-fe287e00-49bb-11ea-849a-b70524a67961.png">

Am I doing something wrong here?

**Comment by lbalmaceda** [comment]
The stack trace is stripped but it seems some variable you are using is null. Can you provide a full-text version of it? So we can pinpoint the line where this crash is happening.

**Comment by smedic** [comment]
As I can see, crash is inside of AuthenticationActivity, not in my code.  My code is copied above the screenshot.

**Comment by lbalmaceda** [comment]
The stack trace points to [this line](https://github.com/auth0/Auth0.Android/blob/master/auth0/src/main/java/com/auth0/android/provider/LogoutManager.java#L55) in the `LogoutManager` class, which is calling the callback's onSuccess with `null` because you were just logged out successfully (and there's nothing to pass you down the callback). I guess the `Void` type in Kotlin expects it to have a value other than null, or else it would have been marked as optional in the interface declaration. Is that something you can do or it doesn't let you? I'd try:
- Use `Void?` instead on the `VoidCallback` implementation
- Use `Unit`, which is the Void for Kotlin.

**Comment by lbalmaceda** [comment]
@smedic were you able to go around this issue?

**Comment by smedic** [comment]
Yes, it works now. Thanks for help @lbalmaceda !

**Comment by lbalmaceda** [comment]
I'm curious, which option fixed this? Was it `Unit`?
