### ISSUE TITLE
SecureCredentialsManager's tokens expiration checks contains bug.

### ISSUE THREAD

**Issue by Tans5** [auth0/Auth0.Android#293]
```java


    private void continueGetCredentials(final BaseCallback<Credentials, CredentialsManagerException> callback) {
        ...
        // Here should use expires time in storage(key is KEY_EXPIRES_AT) as judgment.
        if (credentials.getExpiresAt().getTime() > getCurrentTimeInMillis()) {
            callback.onSuccess(credentials);
            decryptCallback = null;
            return;
        }
        ...
    }

```

**Comment by lbalmaceda** [comment]
👋 Thanks for your report.

Actually, before you get to `continueGetCredentials` you must have called `getCredentials`. And the first thing that is being done is checking for valid stored credentials. See https://github.com/auth0/Auth0.Android/blob/master/auth0/src/main/java/com/auth0/android/authentication/storage/SecureCredentialsManager.java#L192-L195.

This check above considers the right Expires At value, the stored one, and not the one on the credentials. So while the conditional you pointed should use the stored one, there's no bug since the credentials are valid at the time you called this function.

In the worst-case scenario, what could happen is that the manager doesn't give you back the stored Credentials with a good ID Token because it considers the Access Token has already expired, which is really edge case. The only way this could happen is if the expiration occurs in between your call to `getCredentials` and the invocation of the callback you passed with the result/error. Furthermore, when this rare scenario happens, if a Refresh Token is available it will attempt to renew the Credentials with it. 

Let me anyway add a test for the authentication part when the Credentials have expired. And let's change that into the right value as you pointed out for the sake of consistency across the class.

**Comment by luckpoint** [comment]
@lbalmaceda 
Thank you so much for your clarification!
```
public void getCredentials(@NonNull BaseCallback<Credentials, CredentialsManagerException> callback) {
    if (!hasValidCredentials()) {
        callback.onFailure(new CredentialsManagerException("No Credentials were previously set."));
        return;
    }
```
when hasValidCredentials() which checks `expiresAt <= getCurrentTimeInMillis()` returns false, subsequent processing (apiClient.renewAuth) is not called.

There is an inconsistency between validation logics of CredentialsManager#getCredentials and SecureCredentialsManager#getCredentials. Is it ok?

**Comment by lbalmaceda** [comment]
@luckpoint That expires at value comes from the storage. In order to be there, first you'd have to save credentials. 

The save method is the one that contains the logic for checking which time is lower or closer to today, if the id token or the access token expires at. 

When that value is retrieved, it is safe to compare against the current time since the value that was stored is still representing the min between both expires at.

**Comment by Tans5** [comment]
@lbalmaceda Thanks for your reply.
SecureCredentialsManager can only check ACCESS Token and can't check ID Token. So when ID Token was expired and call renew method to get a new ID Token. It is a good solution.
CredentialsManager can check ACCESS Token and ID Token, but SecureCredentialsManager can't. In my view, it's seems strange. And if manager can't refresh ID Token, credentials needs us storage and manage,  manager seems useless? So I think SecureCredentials should check ID Token.

**Comment by lbalmaceda** [comment]
@Tans5 That is what is currently doing. Check these lines corresponding to the `saveCredentials` method of the `SecureCredentialsManager`:

https://github.com/auth0/Auth0.Android/blob/master/auth0/src/main/java/com/auth0/android/authentication/storage/SecureCredentialsManager.java#L147-L156

The rationale is what I put on my previous comment.
