### ISSUE TITLE
Can we upgrade the OkHttp version?

### ISSUE THREAD

**Issue by ssudaraka** [auth0/Auth0.Android#311]
Auth0.Android is currently using an old version of OkHttp (2.7.5). This makes using a performance monitoring tool like Firebase Performance Monitoring not possible because it requires at least okhttp 3.0.0.

**Comment by lbalmaceda** [comment]
@ssudaraka 👋 changing to OkHttp +3.x is a breaking change, that's why a change like that is not possible on the current version of the library. We're evaluating the options we have to update that.

I'll close it since this has [already been asked](https://github.com/auth0/Auth0.Android/pulls?q=okhttp) several times in the past.
