### ISSUE TITLE
How we should work with multi-tenancy with Auth0?

### ISSUE THREAD

**Issue by itscorey** [auth0/Auth0.Android#312]
Hi people 👋,

I was checking Auth0 documentation and I didn't found anything related to how we can manage user session/credentials in multi-tenancy environment.

I've a flow where user can sign-in with username/password and another flow for **Single Sign-on** where the user can input its tenant, then we'll authenticate him using its tenant info (different client id and domain).

How we can manage Auth0 and Credentials? For example, for the default flow with username/password I can just give Auth0 instance with **my** clientId and domain, right?

But for SSO I need to provide an instance of Auth0 with its **Tenant** clientId and domain. That is also ok, but the real question is with `SecureCredentialsManager` (or just credentials manager), I'll need to provide the specific Auth0 instance or it doesn't care about it?

For example:

With Default sign-in flow we have this manager:

```Kotlin
SecureCredentialsManager(app, AuthenticationAPIClient(Auth(clientid, domain), storage))
```

For SSO flow we will need another manager:

```Kotlin
SecureCredentialsManager(app, AuthenticationAPIClient(Auth(tenantClientId, tenantDomain), storage))
```

Is the example above the right way to do that? If so, I think it would be better to have a Builder on top of Auth0 where we can change and build a new instance easily (Builder could also be reusable like OkHttpClient does).

I think the provision of a default Auth0 for tenants will break credentials manager was it should renew using the tenant clientid and domain. 🤔

**Comment by lbalmaceda** [comment]
I don't know what's the right approach here. It's the first time I read a requirement of logging in the user twice with separate identity providers. 

Something you should consider is making sure the Storage instance you're passing on each call uses a different key for storing the values, so they are not overwritten. 

The `AuthenticationAPIClient` instance is only needed by the credentials manager in order to refresh the credentials when they expire, using the refresh token _when available_. This is the [only line](https://github.com/auth0/Auth0.Android/blob/master/auth0/src/main/java/com/auth0/android/authentication/storage/SecureCredentialsManager.java#L269) that uses it.

**Comment by itscorey** [comment]
@lbalmaceda Thank you for your answer. I think I didn't ask the question in the best way, sorry for causing this confusion! My flow doesn't do logging twice, the user can logging with its credentials **or** if him is from an enterprise, he can use SSO login, which uses an instance of `Auth0` created using its tenant informations (authUrl and clientId).

My **real question** is: if the user is logged in using a Tenant, when instantiating `AuthenticationAPIClient` for token renew, `Auth0` instance will need to be created using the same tenant's credentials used to logging, right?

**Comment by lbalmaceda** [comment]
Yes. The tokens you receive are associated to your Auth0 client id and your Auth0 tenant. If you need to renew those credentials with that refresh token, you'd need to use the same client id and tenant used originally. Otherwise, the server will reject that request.
