### ISSUE TITLE
OIDC conformant by default?

### ISSUE THREAD

**Issue by gardyna** [auth0/Auth0.Android#313]
Is there a reason the Auth0 sdk is not set to OIDC conformant by default?

### Describe the problem you'd like to have solved

I'm always frustrated when I have to set isOIDCConformant to true each time the API is used. also when it's a small thing that is quite easy to forget

### Describe the ideal solution

having the value set to true by default would solve my issue, but current behaviour with the option of being able to set OIDCConformant at a global level through gradle (or an XML settings file) would also prevent errors of this kind with minimal extra code added on my side while still maintaining compatibility with old (non OIDCConformant code)

## Alternatives and current work-arounds

every user must manually have a line at every point Auth0 is instantiated to declare it as OIDCConformant (current behaviour)

### Additional context

This request falls squarely into the "nice to have" column but I don't think it would be that difficult of a thing to implement and would make the SDK a bit nicer to use

**Comment by lbalmaceda** [comment]
💯 thanks for raising this. Doing this today would be a breaking change since there are methods that check this flag to make calls to the right/corresponding endpoints. e.g. the login or renew auth methods.

Definitely, having an OIDC only SDK is something we will take into consideration for the next major. For now, is there anything we can do in terms of the docs to improve this experience?

**Comment by lbalmaceda** [comment]
We plan on making a new major release for Q4, including this suggestion. Since we're not going to be working on it for ~3 months I'll close this issue.
