### ISSUE TITLE
Credentials lost after update

### ISSUE THREAD

**Issue by codeincontext** [auth0/Auth0.Android#324]
### Description

We just released a new version of our app (upgrading to Android X) and it seems like every user has lost their credentials:

> A change on the Lock Screen security settings have deemed the encryption keys invalid and have been recreated. Any previously stored content is now lost. Please, try saving the credentials again.

It's possible this is our fault, but the cause seems very opaque to us. Is it possible that the error message is catching other types of error as well?

https://github.com/auth0/Auth0.Android/blob/dc19c45c01fd5a5d7d023755dc96432ff63ee284/auth0/src/main/java/com/auth0/android/authentication/storage/SecureCredentialsManager.java#L170-L178

### Reproduction

- Follow examples for `SecureCredentialsManager` 
- Update app (unclear what changes cause this problem)

Thanks
Adam

**Comment by lbalmaceda** [comment]
@codeincontext I think the issue might be on the last PR we introduced [here](https://github.com/auth0/Auth0.Android/pull/315). Our intent was to use a new key alias for storing the credentials from now on with a prefix on it. However, it looks like the `hasValidCredentials()` method is not aware of the alias used at save time, and would still report previously-stored credentials as "valid" even if those are unreacheable because they were encrypted with a different alias.

Saving new credentials (e.g. re-authenticating your users) resolves this. I'm tracking this internally as `SDK-1868`.

**Comment by codeincontext** [comment]
👍 

That makes sense. Thank you for investigating

**Comment by lbalmaceda** [comment]
Patch released as `1.24.1`. Thanks again for reporting.

To clarify the expected (now fixed) behavior: When you migrate to 1.24.1+ the first time your users open the app, the `hasValidCredentials()` method will return "false" because it won't find any under the new alias. Since you should be handling that "no log in available" scenario, you will prompt the user for authentication and save the tokens as you would normally.

**Comment by Maksym-Motornyi** [comment]
This PR actually allow to migrate without loosing creadentials:
https://github.com/auth0/Auth0.Android/pull/481
