### ISSUE TITLE
Callback not working when User is already logged in or during Logout

### ISSUE THREAD

**Issue by sonusurender** [auth0/Auth0.Android#347]
Hi,

I am trying to use the mobile SDK but i am facing few issue as follows:
1. When i am trying to login if session is already there.
2. and When I try to logout.

I get the below screen:
![Screenshot_1600444616](https://user-images.githubusercontent.com/8831886/93619092-c378d080-f9f5-11ea-8314-01dc9820aa63.png)

It seems the **Callback URL** not found. I checked the logs in dashboard and it says that logout get successful but redirection is not happening.

**If there is issue in redirection url then login also shouldn't happen but login is working.**

So just wanted to know did i miss something or there is something wrong?

**SDK Version: 1.26.1
Device OS Version :  Pie (28)**

Let me know if you need more info.

Thanks

**Comment by lbalmaceda** [comment]
Does this happen with any browser app or one in particular? Does it happen with Auth0 database connections or social connections?

**Comment by sonusurender** [comment]
I have tried with 3-4 apps and the behaviour is same.
I am using Auth0 database connection.

**Comment by sonusurender** [comment]
It's now working. I had to change the **scheme** from **https** to **demo**.

Thanks

**Comment by lbalmaceda** [comment]
@sonusurender I assume the reason you see that, is because you were using "Android App Links" (or maybe just regular deeplinks with scheme of "https"). Those URLs are designed to be open **both in the browser and in your app**, so unless you provide a page template in that path, you will see that 404 error or white page. How that redirection will be handled, if not blocked, depends on each browsers' implementation and is outside of this SDKs scope.

See from the [official app links docs](https://developer.android.com/training/app-links):

![image](https://user-images.githubusercontent.com/3900123/93890705-03bfa380-fcc1-11ea-8144-84115962edb0.png)
