### ISSUE TITLE
Preemptive Credentials refresh [SDK-1819]

### ISSUE THREAD

**Issue by skjolber** [auth0/Auth0.Android#349]
### Describe the problem you'd like to have solved
We're building a ticket inspection app. We want to avoid interaction with the authorization server as much as possible during the inspection session, which can last from a few minutes to a few hours (all limited by the authorization server settings). 

### Describe the ideal solution

We would like preemptively refresh the access-token, and/or trigger a new (manual) login if the refresh-token is about to expire. Ideally some kind of `forceRefresh` parameter could be added and we would get the relevant timestamps from `Credentials`.

## Alternatives and current work-arounds

Get the credentials, look at the id-token expire time, clear them if not acceptable.

### Additional context

[SecureCredentialsManager](https://github.com/auth0/Auth0.Android/blob/master/auth0/src/main/java/com/auth0/android/authentication/storage/SecureCredentialsManager.java)

**Comment by lbalmaceda** [comment]
Hey @skjolber ! 👋  If I understand correctly what you're asking, you need the "Credentials Managers" to expose some way to manually refresh the tokens, even when they have not expired yet and shouldn't be refreshed. Is that correct?

If that's the case, one of the solutions we implemented in iOS and want to bring to Android as well is passing some TTL value on the `getCredentials` call, so that you can specify that you require an access token that will last for at least X (TTL) seconds. 

Would a solution like that work for you? If so, I can link this issue to that card.

**Comment by skjolber** [comment]
That is right. Yes, I think the TTL approach you're describing will work for us :+1:

**Comment by lbalmaceda** [comment]
Excellent. Tracking under `SDK-1819`.

**Comment by lbalmaceda** [comment]
@skjolber the 2 PRs above add support for this in both credential managers. I'll have it released in the next minor.

**Comment by lbalmaceda** [comment]
Feature added in PRs 363 and 369
