### ISSUE TITLE
Logout callback is not working

### ISSUE THREAD

**Issue by monochkov** [auth0/Auth0.Android#357]
The issue is similar to https://github.com/auth0/Auth0.Android/issues/347.

The problem is when I try to logout using Android SDK I get white page with "Not Found" error. **Logout callback is not called, but browser cache is cleared.**
For logout I'm using:
```
WebAuthProvider
                .logout(new Auth0(getContext()))
                .start(this, logoutCallback)
```
I investigated a bit and found an issue:
`AuthenticationActivity.java` file `protected void onResume()` function (line 73) - when this method is called for logout, `intentLaunched = false` (because browser is opened first time) and as a result `launchAuthenticationIntent();` is called (line 82) with logout url, but `deliverAuthenticationResult(authenticationIntent);` (line 90) should be called to invoke callback.

Did I miss something or is this an issue?

**SDK Version: 1.27.0** 
**Device API Version : 28**

Let me know if you need more info.

Thanks!

**Comment by lbalmaceda** [comment]
@monochkov You are probably using Android App Links and since there's no page that you could interact with, the browser will block the auto-redirect. This is a Chromium "feature", so every browser based on Chromium will have the same behavior.

The recommendation is to use as callback URL a site you own that can display a button or link to take the user back to the app (using the link you are using today as callback URL). This is what [Google recommends](https://developer.android.com/training/app-links) as a fallback when using app links:

![image](https://user-images.githubusercontent.com/3900123/95352447-a28af900-0898-11eb-887f-ba12271db044.png)

Alternatively, you could use custom schemes e.g. "com.mycompany.myapp://mycallback". This is explained in the readme. https://github.com/auth0/Auth0.Android#a-note-about-app-deep-linking

How can we improve that documentation?

**Comment by monochkov** [comment]
@lbalmaceda Thanks for the answer.
I just checked with Firefox (non-Chromium) browser - I am not returned back to app neither after login and after logout - received empty page with "Not found" message in both cases. But I can press "3 dots" in menu and choose "Open in app" - then I will be redirected to app. I guess this is expected behavior because browser handles https automatically by default.

My question is: Will custom scheme fix this problem? I assume yes, because only my app will be able to handle my custom scheme. But please confirm my assumption.

**Comment by lbalmaceda** [comment]
I thought Firefox was Chromium-based. Oh well, then Firefox also has this problem. 

> I guess this is expected behavior because the browser handles https automatically by default.

Honestly, if your app got its deep links domain verified (app links verification passed), the chosen app to resolve the intent should be without a question your app, even if you are visiting that from within a browser app. That's what Chrome and others do, at least. Firefox has this differentiation in the UX that they require you as a user to manually click a button in their menu to open that intent in a supported app. Which going back to what Google recommends for App Links, shouldn't be a problem since you should be hosting HTML content in that callback URL in case this redirection gets blocked. 

I've created an issue a few days ago asking for more feedback https://github.com/mozilla-mobile/fenix/issues/15202.

> My question is: Will custom scheme fix this problem?

Yes, it will resolve the redirection problem as long as no other app in the device has registered for the same intent filter. You could try using the package name for the scheme part (must be all lowercase) to reduce the chances of clashing. Still, you should know that using custom schemes won't prevent another app from registering an intent filter for the same callback URL. Meaning that if more than one application can handle the callback, both would be offered to the user to pick from. Does that make sense? And repeating my previous question, as a developer, how would you expect this to be surfaced in the readme, how can we improve that? 

Cheers

**Comment by monochkov** [comment]
@lbalmaceda Thanks for your help! Custom scheme resolved my issue.

> how would you expect this to be surfaced in the readme, how can we improve that?

So, since default https scheme is not working properly in all browsers, I would suggest you to recommend customers to use their custom scheme (package name for example). Also I would recommend to mention that in separate topic in your README like for default https scheme: https://github.com/auth0/Auth0.Android#authentication-with-universal-login .
But then say like "if you are not specify you custom scheme, you will use default https scheme. To configure it please enable Android App Links: https://auth0.com/docs/applications/enable-android-app-links-support and follow docs: https://github.com/auth0/Auth0.Android#authentication-with-universal-login ".

I would suggest you to write it in you docs in official site and in README in GitHub repo to avoid any confusions.

Thanks you so much,
Best regards.
