### ISSUE TITLE
SecureCredentialsManager.getCredentials fails when minifyEnabled is true

### ISSUE THREAD

**Issue by sproctor** [auth0/Auth0.Android#462]
### Describe the problem

https://github.com/auth0/Auth0.Android/blob/main/auth0/src/main/java/com/auth0/android/authentication/storage/SecureCredentialsManager.kt#L305

bridgeCredentials fails to properly parse json when shipping a minified build. Adding proguard rules found here works around this issue: https://medium.com/@harryaung/mysterious-null-crash-with-gson-serializedname-fields-when-r8-proguard-is-on-f8a4bd036e34

This issue is new in 2.0

### What was the expected behavior?

minifyEnabled to work without adding extra rules.

### Environment

Auth0.Android 2.0.0

**Comment by lbalmaceda** [comment]
Thanks. I'll add these rules to the consumer proguard rules so that it gets shipped with the next release. 

In the meantime, and for anyone looking for a solution in 2.0.0, add the following rules to the proguard rules file in your project.

```
-keepclassmembers,allowobfuscation class * {
  @com.google.gson.annotations.SerializedName <fields>;
}
-keep,allowobfuscation @interface com.google.gson.annotations.SerializedName
```

I'll tag this as needs-investigation to signal that the follow-up is on my side.
