### ISSUE TITLE
When get stored credentials, allow token not to refresh automatically

### ISSUE THREAD

**Issue by RowanG1Bilue** [auth0/Auth0.Android#477]
### Describe the problem you'd like to have solved

We need to update the scope at the point of token refresh, and when getting the credential, we would like to get the existing credential without auto refresh, and manually refresh the token with updated scopes.

### Describe the ideal solution

As above.

## Alternatives and current work-arounds

We currently store the credential separately, but this introduces more code and higher likelihood of bugs.

### Additional information, if any

**Comment by lbalmaceda** [comment]
I believe you should be able to do this today using the method that takes the `scope` attribute. For the `CredentialsManager` that should be [this one](https://github.com/auth0/Auth0.Android/blob/main/auth0/src/main/java/com/auth0/android/authentication/storage/CredentialsManager.kt#L71-L74).

As a reminder, you can never ask for more scope than the one that was originally granted. You can, however, ask for less scope than before.

Hope that helps

**Comment by RowanG1Bilue** [comment]
Thank you so much for responding. We have tried your approach, however we saw that when passing the scope and minTtl to the getCredential method, the token refreshes to a different value on every call. Without the scope, the token does not change on each call.

**Comment by lbalmaceda** [comment]
The token that is stored will only be returned if it satisfies the `scope` and the minimum duration that you ask through the `minTtl` parameter, while it's considered still valid (i.e. not expired). In any other situation, a network request will be made to ask for new credentials. Upon request success, those new credentials are stored. As long as the token's expiration date satisfies the `minTTL` value, if you always ask for the same scope, you should always receive the same local token. 

Note that if the stored token has multiple scopes and you try to obtain a token with a subset of those, a network request will always be made. This is because, while the token can already satisfy that scope subset, the reason you'd want a more restrictive token like that is to lower the risks that exposing it might carry. 

Does that help?

**Comment by RowanG1Bilue** [comment]
I really appreciate your comments. We refresh scope was the same as the original scope, so it would appear that the issue had to do with the minTtl- we tried different settings for MinTtl in front end client, but could not get it right. We get the exception:
`com.auth0.android.authentication.storage.CredentialsManagerException: The lifetime of the renewed Access Token (0) is less than the minTTL requested (900). Increase the 'Token Expiration' setting of your Auth0 API in the dashboard, or request a lower minTTL.`
Of course, it would appear that we need to adjust the dashboard settings, but we have not needed to do this on iOS- which used the renew method. When we use the renew method on Android, the refresh is also fine.

**Comment by lbalmaceda** [comment]
What the error says is that the server issued an access token for the API (audience) you have requested, that has an expiration time lower than the min TTL that you are requesting in this call. If that's the case, what the error suggests is to check that access token duration setting in the specific API that you are requesting access to. Have you checked that? Is weird that if for iOS you are using the exact same API and passing the same minTTL values that this behaves differently on Android. But I cannot help without more details.

**Comment by lbalmaceda** [comment]
@RowanG1Bilue I'm going to close this now. If you have further questions feel free to reply here.
