### ISSUE TITLE
Test artifact for login

### ISSUE THREAD

**Issue by skjolber** [auth0/Auth0.Android#515]
### Describe the problem you'd like to have solved
Writing Espresso tests for apps which login to Auth0 is cumbersome. While this sounds trivial, it really is not trivial to get it stable.

### Describe the ideal solution
A test artifact which accepts a username and password, and interacts with Auth0's web view. This includes all "first use" dialog dismissals like "Help build a better keyboard", "Accept terms" and such, plus entering and submitting the form.

### Additional information, if any
Testing in the cloud usually means slow network and/or slow devices. Specifying the correct browser is also necessary for some devices. Also devices in the cloud and developer devices might not have the same language. In some cases buttons are not visible etc.

We can contribute the code we currently have as a starting point.

**Comment by lbalmaceda** [comment]
We don't have any integration tests in the library today. I think they are a good addition and will help test at least the most common authentication use case of end-to-end authentication using web auth. That said, from our side, this would require a bit of extra work to figure out an approved provider to run these in and set up the CI pipeline for that. 

After reviewing this with my team, we will accept your existing tests as a PR and we will set those up to run locally, instead of the CI, for now.

**Comment by skjolber** [comment]
Good, and note that what I am aiming for is a test artifact + test app for running integration tests. We're using testlab from CircleCI, if you want I can add some example docs / scripts.

**Comment by poovamraj** [comment]
Hi, @skjolber we are planning to implement Integration Testing for the SDK using Appium. Since we are tracking this internally and this ticket has been inactive for quite some time now we will close this ticket for now. Please feel to reopen this if you still have any doubts regarding this.

**Comment by skjolber** [comment]
@poovamraj I am sorry for the delay, we have had ongoing problems and now I think the best way to do integration testing in an app is to bypass the login gui by using a machine-to-machine client instead.
