### ISSUE TITLE
Using web view to login instead of browser app

### ISSUE THREAD

**Issue by ycagri** [auth0/Auth0.Android#541]
### Describe the problem you'd like to have solved

I want to use Android web view instead of Auth0 browser app. However, it is stated in [here](https://community.auth0.com/t/using-webview-to-login-on-android-instead-of-browser/66079) that Google blocks oAuth requests made via embedded browsers.

### Describe the ideal solution

Google error just tells that user-agent is not permitted. It is possible to use a fake user agent to hack this behavior. The code below perfectly works for getting the code.

## Alternatives and current work-arounds

`webview.settings.userAgentString = "Mozilla/5.0 (Linux; Android 4.1.1; Galaxy Nexus Build/JRO03C) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.166 Mobile Safari/535.19"`

### Additional information, if any

I have one question: Does using same user agent cause any problems in Auth0 flow?

**Comment by poovamraj** [comment]
Hi @ycagri we currently do not support login using web view due to security concerns. Supporting this in our SDK wouldn't be the right approach so we won't be able to take this feature request forward. We strongly suggest using the custom tabs approach as it is the current norm and many Android users got used to this flow. You can customize the Custom Tabs using `CustomTabsOptions` we provide. I'll close this feature request for now. Do let us know if you need any further help in this.
