### ISSUE TITLE
Query regarding AuthenticationException with a0.sdk.internal_error.unknown code

### ISSUE THREAD

**Issue by alvindizon** [auth0/Auth0.Android#547]
We have logged many `AuthenticationException` events from our app with code `a0.sdk.internal_error.unknown` and description `Received error with code a0.sdk.internal_error.unknown`--our logs show that these events happen when users open our app, presumably after a period of inactivity, which triggers our app to call `renewAuth`. The `onFailure` callback in `AuthenticationCallback` is then triggered with the said error code and description. What could be the cause of such errors? We checked and `isNetworkError` is false.

**Comment by poovamraj** [comment]
Hi @alvindizon, Unknown error can be thrown in cases where we do not have to get the error code from the server or when the exception didn't happen because of a network error like a timeout. 

However, it can happen in cases like where the server is not reachable because the internet is switched off and `UnknownHostException` is thrown. Do you think it could be this or a similar case that is causing the unknown error?

**Comment by alvindizon** [comment]
Hi @poovamraj, if `UnknownHostException` is thrown, would `isNetworkError` be true? Because in our code, we are only logging events with code `a0.sdk.internal_error.unknown` and description `Received error with code a0.sdk.internal_error.unknown` if `isNetworkError` is false.

**Comment by poovamraj** [comment]
`isNetworkError` will be false if it is an `UnknownHostException`. Network error is shown only when an API call fails because of network reasons like timeout. The best way would be to get the whole stack trace to really understand the cause for the unknown issue. Hope this helps!

**Comment by poovamraj** [comment]
Hi @alvindizon, Hope this helped with your issue. Please feel free to reopen this ticket if you have any more doubts regarding this.
