### ISSUE TITLE
MFA pairing using withParameters

### ISSUE THREAD

**Issue by Nitishreddy787** [auth0/Auth0.Android#557]
Hi,

 I am using auth0 2.7.0 version, After successful login, we are calling an native api which returns an status saying that MFA has to attached, after that when I am trying to navigate user to pair the mfa using below method

WebAuthProvider.login(account)
                .withParameters(mutableMapOf( "prompt" to "mfa-push-welcome"))

is showing Oops!, something went wrong page

Or is there any other option to navigate  the user to MFA PUSH WELCOME page.

Thanks
Nitish

**Comment by poovamraj** [comment]
Hi @Nitishreddy787 👋 

> After successful login

Do you use Native APIs to login a user instead of Universal Login?

> we are calling an native api which returns an status saying that MFA has to attached

Can you share us the error code and more details on this error

> Oops!, something went wrong page

Are you sure the [Callback URL](https://github.com/auth0/auth0.android#authentication-with-universal-login) are set properly in the Auth0 dashboard?

**Comment by poovamraj** [comment]
Hi @Nitishreddy787, any update on this?

**Comment by Nitishreddy787** [comment]
Hi, @poovamraj we have a custom parameter for MFA, passing it to WebProvider.login solved my issue.

Sorry for late response.

**Comment by poovamraj** [comment]
Awesome! 👍 we are closing this issue then. Please feel to free to reopen it if you have anymore doubts!
