### ISSUE TITLE
MFA Screen is missing, when reinstalling the application.

### ISSUE THREAD

**Issue by Nitishreddy787** [auth0/Auth0.Android#573]
Hi,

I am using auth0 2.7.0 version, Login using a WebAuthProvider with email, password and MFA and user is successfully logged in. User didn't signed out and, when user a uninstalls the app and reinstall, Login flow is not asking for MFA code, it is directly returning the success callback with email and password.

Sample code:

WebAuthProvider.login(account)
                .withScheme(packageName.toString())
                .withScope("openid profile email")
                .withParameters(mutableMapOf( "prompt" to "login"))
                .start( ){  }
                
  
Thanks,
Nitish

**Comment by poovamraj** [comment]
@Nitishreddy787 The login happens and the session is stored in the browser. This is how single sign-on works, which is why the session will be maintained if the user logs in and uninstalls the app without logging off.

Hope this helps, let me know if you have more doubt on this, please feel free to reopen the issue.
