### ISSUE TITLE
Open class Auth0 is effectively final since 2.0.0

### ISSUE THREAD

**Issue by julia-martemianova** [auth0/Auth0.Android#617]
### Describe the problem you'd like to have solved
The problem was previously described here: https://github.com/auth0/Auth0.Android/issues/611. Creating this issue to reopen it.
The scenario in which the URL is changing: for the social login connection we have the following path which we cannot change: `/connect/authorize`. To make it work we have to maintain a fork of the library with a small customisation.

### Describe the ideal solution
Add the open keyword to each fun/val/var in Auth0.kt.

### Alternatives and current work-arounds
N/A

### Additional information, if any
Minimal repro to show what's the problem:
```kotlin
open class Auth0 {
    public val authorizeUrl: String get() = "..."
}
class MyAuth0 : Auth0() {
    // [OVERRIDING_FINAL_MEMBER] 'authorizeUrl' in 'Auth0' is final and cannot be overridden
    override val authorizeUrl: String get() = "/somethingelse/..."
}
```

**Comment by poovamraj** [comment]
Hi @julia-martemianova 👋 

This seems to be a popular feature request. I guess instead of opening the Auth0 class, we can make the `authorizeUrl` mutable similar to `networkingClient` (Need to verify this doesn't have any unwanted side effects though)

But before that can you confirm which Social Login requires such scenario? As it is used only in Web Authentication and currently in Auth0 universal login we can't change the Authorization URL.

**Comment by julia-martemianova** [comment]
Hi @poovamraj  thanks for getting back to me!
I double checked. We need to test our identity server integration for social login in production before releasing it. For that we need a different path to initiate the social login connection. I you could make the `authorizeUrl` mutable, that would be great. Because apart from the pain of maintaining a fork we are also not able to use latest versions of the library.

**Comment by poovamraj** [comment]
@julia-martemianova Just to confirm, this " identity server" is not Auth0?

**Comment by julia-martemianova** [comment]
> Just to confirm, this "identity server" is not Auth0?
@poovamraj yes

**Comment by poovamraj** [comment]
@julia-martemianova since this SDK is designed for working with Auth0 the requested feature is missing in the newer versions. Due to other priorities in the pipeline, we couldn't concentrate on this request right away. However, we wouldn't mind merging a PR with the requested feature and can help you with it from our end.

**Comment by poovamraj** [comment]
Hi @julia-martemianova, we have created a PR to fix this - https://github.com/auth0/Auth0.Android/pull/622. Do check it out

This should be released once it is merged. We will keep you posted on the release. We will close this issue for now, please feel free to reopen it if you have any doubts
