### ISSUE TITLE
Transitive dependency changes app's name

### ISSUE THREAD

**Issue by laramartin** [auth0/Auth0.Android#646]
### Describe the problem
We are using your library and updated to version [2.9.0](https://github.com/auth0/Auth0.Android/releases/tag/2.9.0).

After we created a release build, we noticed that our app name was changed to "Android Browser Helper".

We found out that Auth0 is pulling the "Android browser helper" library as a transitive dependency. This dependency was the culprit overriding the standard app name. We have our strings in a different module than the app module (it should be ok to do this!), therefore the browser helper's name was taking precedence, as they declare it in their app module.

I raised an issue here as well https://github.com/GoogleChrome/android-browser-helper/issues/419 

### Environment

- **Version of this library used:** v2.9.0
- **Other modules/plugins/libraries that might be involved:** [android-browser-helper](https://github.com/GoogleChrome/android-browser-helper/issues/419)

**Comment by poovamraj** [comment]
Hi @laramartin thanks for raising this. Looks like android-browser-helper will be fixing this issue. We can pull it in once it is fixed there. I am following the issue there. Until then I guess you can use `tools:override` to ensure the correct app_name is used. We will close the issue here for now. Please comment here if you have more to add and we can reopen this issue.

**Comment by laramartin** [comment]
thank you for following up and for the suggestion. I should have mentioned that we ended up moving our `app_name` string to the `app` module :) 

No need to reopen, we wanted to only raise awareness here in case someone else searches for this. 

Cheers!
